<!-- インクルードエリア -->
<meta name="viewport" content="width=device-width, initial-scale=1.0" />
<meta name="keywords" content="<?= htmlspecialchars($page_info['keywords']); ?>" />
<meta name="description" content="<?= htmlspecialchars($page_info['description']); ?>" />

<?= $px->get_contents_manifesto(); ?>

<link rel="stylesheet" href="<?= htmlspecialchars($px->path_plugin_files('/css/common.css')); ?>" type="text/css" />

<!-- / インクルードエリア -->
